# Generated by Django 5.1.3 on 2024-12-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
