# Generated by Django 5.1.3 on 2025-01-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kona', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='encrypted_content',
        ),
    ]
